---
version: 2
updates:

  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
      time: '15:20'
    target-branch: dev

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '15:20'
    target-branch: dev
