name: Sync Fork

on:
  schedule:
    - cron: '0 18 * * 1' # At 18:00 on Monday.
    #- cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ github.token }}
          repo: Visual-Compose-Fork
          owner: scto
          base: main
          head: main
          merge_method:	merge
